
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Tue Mar 04 20:14:30 CST 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 49;
  static final int TIMES = 18;
  static final int GT = 24;
  static final int ARROW = 66;
  static final int DIVASSIGN = 65;
  static final int CONST = 51;
  static final int GE = 25;
  static final int PERIOD = 77;
  static final int REGISTER = 39;
  static final int ENUM = 55;
  static final int RBRACK = 13;
  static final int SIZEOF = 44;
  static final int COMMA = 7;
  static final int RBRACE = 15;
  static final int RPAREN = 11;
  static final int LBRACK = 12;
  static final int LT = 22;
  static final int INCREMENT = 70;
  static final int SUBASSIGN = 67;
  static final int DOUBLE = 47;
  static final int BWISEANDASSIGN = 72;
  static final int STRUCT = 42;
  static final int LBRACE = 14;
  static final int LPAREN = 10;
  static final int MODASSIGN = 73;
  static final int NOT = 38;
  static final int TILDE = 74;
  static final int LE = 23;
  static final int VAR = 36;
  static final int BITWISEAND = 78;
  static final int FLOAT = 50;
  static final int GOTO = 54;
  static final int EQ = 20;
  static final int LSHIFTASSIGN = 59;
  static final int MODULUS = 79;
  static final int LONG = 53;
  static final int PLUS = 16;
  static final int DIVIDE = 19;
  static final int WHILE = 31;
  static final int UNION = 48;
  static final int ASSIGN = 28;
  static final int CHAR = 56;
  static final int ADDASSIGN = 69;
  static final int DO = 33;
  static final int FOR = 32;
  static final int VOID = 52;
  static final int EXTERN = 46;
  static final int RETURN = 45;
  static final int ELSE = 30;
  static final int BREAK = 34;
  static final int FUN = 35;
  static final int INT = 6;
  static final int STRING_LITERAL = 3;
  static final int EOF = 0;
  static final int SEMICOLON = 9;
  static final int MULASSIGN = 71;
  static final int ELIPSES = 60;
  static final int DECREMENT = 68;
  static final int MINUS = 17;
  static final int OR = 27;
  static final int error = 1;
  static final int DECIMAL_LITERAL = 4;
  static final int CONTINUE = 40;
  static final int IF = 29;
  static final int BWISEOR = 75;
  static final int ID = 2;
  static final int COLON = 8;
  static final int BWISEXOR = 76;
  static final int BWISEORASSIGN = 61;
  static final int RSHIFTASSIGN = 58;
  static final int VOLATILE = 37;
  static final int CHAR_LITERAL = 5;
  static final int RSHIFT = 63;
  static final int BWISEXORASSIGN = 62;
  static final int NEQ = 21;
  static final int AND = 26;
  static final int STATIC = 43;
  static final int LSHIFT = 64;
  static final int TYPEDEF = 41;
  static final int AUTO = 57;

  /* non terminals */
  static final int bitfield_list = 30;
  static final int struct_declaration_list = 20;
  static final int declaration_list = 25;
  static final int initializer = 48;
  static final int pointer_list = 38;
  static final int additive_expression = 7;
  static final int enumerator = 19;
  static final int $START = 0;
  static final int Var = 18;
  static final int compound_statement = 24;
  static final int initializer_list = 47;
  static final int constant_expression = 21;
  static final int initialization = 40;
  static final int struct_or_union = 42;
  static final int primary_expression = 1;
  static final int name = 29;
  static final int logical_or_expression = 15;
  static final int equality_expression = 10;
  static final int exclusive_or_expression = 12;
  static final int cast_expression = 4;
  static final int expression_array_type_list = 34;
  static final int bitfield_value = 31;
  static final int enumerator_list = 23;
  static final int parameter_type_list = 46;
  static final int expression = 17;
  static final int type_parameters = 43;
  static final int unary_expression = 5;
  static final int empty_array_type_list = 32;
  static final int brackets_list = 37;
  static final int type_name = 39;
  static final int postfix_expression = 3;
  static final int logical_and_expression = 14;
  static final int shift_expression = 8;
  static final int and_expression = 11;
  static final int parameter_list = 45;
  static final int empty_array_type = 33;
  static final int expression_array_type = 22;
  static final int inclusive_or_expression = 13;
  static final int assignment_expression = 2;
  static final int type_augments = 36;
  static final int statementordecloration_list = 26;
  static final int comma_operator = 16;
  static final int multiplicative_expression = 6;
  static final int expression_statement = 27;
  static final int parameters = 44;
  static final int struct_or_union_declarator = 41;
  static final int declaration = 28;
  static final int relational_expression = 9;
  static final int type = 35;
}

